// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pb/transaction_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=internal/pb/transaction_grpc.pb.go -destination=internal/pb/mocks/transaction_grpc_mock.go
//

// Package mock_pb is a generated GoMock package.
package mock_pb

import (
	pb "MamangRust/paymentgatewaygrpc/internal/pb"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockTransactionServiceClient is a mock of TransactionServiceClient interface.
type MockTransactionServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceClientMockRecorder
	isgomock struct{}
}

// MockTransactionServiceClientMockRecorder is the mock recorder for MockTransactionServiceClient.
type MockTransactionServiceClientMockRecorder struct {
	mock *MockTransactionServiceClient
}

// NewMockTransactionServiceClient creates a new mock instance.
func NewMockTransactionServiceClient(ctrl *gomock.Controller) *MockTransactionServiceClient {
	mock := &MockTransactionServiceClient{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionServiceClient) EXPECT() *MockTransactionServiceClientMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockTransactionServiceClient) CreateTransaction(ctx context.Context, in *pb.CreateTransactionRequest, opts ...grpc.CallOption) (*pb.ApiResponseTransaction, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTransaction", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockTransactionServiceClientMockRecorder) CreateTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockTransactionServiceClient)(nil).CreateTransaction), varargs...)
}

// DeleteTransactionPermanent mocks base method.
func (m *MockTransactionServiceClient) DeleteTransactionPermanent(ctx context.Context, in *pb.FindByIdTransactionRequest, opts ...grpc.CallOption) (*pb.ApiResponseTransactionDelete, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTransactionPermanent", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseTransactionDelete)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTransactionPermanent indicates an expected call of DeleteTransactionPermanent.
func (mr *MockTransactionServiceClientMockRecorder) DeleteTransactionPermanent(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransactionPermanent", reflect.TypeOf((*MockTransactionServiceClient)(nil).DeleteTransactionPermanent), varargs...)
}

// FindAllTransaction mocks base method.
func (m *MockTransactionServiceClient) FindAllTransaction(ctx context.Context, in *pb.FindAllTransactionRequest, opts ...grpc.CallOption) (*pb.ApiResponsePaginationTransaction, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindAllTransaction", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllTransaction indicates an expected call of FindAllTransaction.
func (mr *MockTransactionServiceClientMockRecorder) FindAllTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllTransaction", reflect.TypeOf((*MockTransactionServiceClient)(nil).FindAllTransaction), varargs...)
}

// FindByActiveTransaction mocks base method.
func (m *MockTransactionServiceClient) FindByActiveTransaction(ctx context.Context, in *pb.FindAllTransactionRequest, opts ...grpc.CallOption) (*pb.ApiResponsePaginationTransactionDeleteAt, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindByActiveTransaction", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationTransactionDeleteAt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByActiveTransaction indicates an expected call of FindByActiveTransaction.
func (mr *MockTransactionServiceClientMockRecorder) FindByActiveTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByActiveTransaction", reflect.TypeOf((*MockTransactionServiceClient)(nil).FindByActiveTransaction), varargs...)
}

// FindByCardNumberTransaction mocks base method.
func (m *MockTransactionServiceClient) FindByCardNumberTransaction(ctx context.Context, in *pb.FindByCardNumberTransactionRequest, opts ...grpc.CallOption) (*pb.ApiResponseTransactions, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindByCardNumberTransaction", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseTransactions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCardNumberTransaction indicates an expected call of FindByCardNumberTransaction.
func (mr *MockTransactionServiceClientMockRecorder) FindByCardNumberTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCardNumberTransaction", reflect.TypeOf((*MockTransactionServiceClient)(nil).FindByCardNumberTransaction), varargs...)
}

// FindByIdTransaction mocks base method.
func (m *MockTransactionServiceClient) FindByIdTransaction(ctx context.Context, in *pb.FindByIdTransactionRequest, opts ...grpc.CallOption) (*pb.ApiResponseTransaction, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindByIdTransaction", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdTransaction indicates an expected call of FindByIdTransaction.
func (mr *MockTransactionServiceClientMockRecorder) FindByIdTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdTransaction", reflect.TypeOf((*MockTransactionServiceClient)(nil).FindByIdTransaction), varargs...)
}

// FindByTrashedTransaction mocks base method.
func (m *MockTransactionServiceClient) FindByTrashedTransaction(ctx context.Context, in *pb.FindAllTransactionRequest, opts ...grpc.CallOption) (*pb.ApiResponsePaginationTransactionDeleteAt, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindByTrashedTransaction", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationTransactionDeleteAt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTrashedTransaction indicates an expected call of FindByTrashedTransaction.
func (mr *MockTransactionServiceClientMockRecorder) FindByTrashedTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTrashedTransaction", reflect.TypeOf((*MockTransactionServiceClient)(nil).FindByTrashedTransaction), varargs...)
}

// FindTransactionByMerchantId mocks base method.
func (m *MockTransactionServiceClient) FindTransactionByMerchantId(ctx context.Context, in *pb.FindTransactionByMerchantIdRequest, opts ...grpc.CallOption) (*pb.ApiResponseTransactions, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindTransactionByMerchantId", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseTransactions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTransactionByMerchantId indicates an expected call of FindTransactionByMerchantId.
func (mr *MockTransactionServiceClientMockRecorder) FindTransactionByMerchantId(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTransactionByMerchantId", reflect.TypeOf((*MockTransactionServiceClient)(nil).FindTransactionByMerchantId), varargs...)
}

// RestoreTransaction mocks base method.
func (m *MockTransactionServiceClient) RestoreTransaction(ctx context.Context, in *pb.FindByIdTransactionRequest, opts ...grpc.CallOption) (*pb.ApiResponseTransaction, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RestoreTransaction", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreTransaction indicates an expected call of RestoreTransaction.
func (mr *MockTransactionServiceClientMockRecorder) RestoreTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreTransaction", reflect.TypeOf((*MockTransactionServiceClient)(nil).RestoreTransaction), varargs...)
}

// TrashedTransaction mocks base method.
func (m *MockTransactionServiceClient) TrashedTransaction(ctx context.Context, in *pb.FindByIdTransactionRequest, opts ...grpc.CallOption) (*pb.ApiResponseTransaction, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TrashedTransaction", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrashedTransaction indicates an expected call of TrashedTransaction.
func (mr *MockTransactionServiceClientMockRecorder) TrashedTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrashedTransaction", reflect.TypeOf((*MockTransactionServiceClient)(nil).TrashedTransaction), varargs...)
}

// UpdateTransaction mocks base method.
func (m *MockTransactionServiceClient) UpdateTransaction(ctx context.Context, in *pb.UpdateTransactionRequest, opts ...grpc.CallOption) (*pb.ApiResponseTransaction, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateTransaction", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTransaction indicates an expected call of UpdateTransaction.
func (mr *MockTransactionServiceClientMockRecorder) UpdateTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransaction", reflect.TypeOf((*MockTransactionServiceClient)(nil).UpdateTransaction), varargs...)
}

// MockTransactionServiceServer is a mock of TransactionServiceServer interface.
type MockTransactionServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceServerMockRecorder
	isgomock struct{}
}

// MockTransactionServiceServerMockRecorder is the mock recorder for MockTransactionServiceServer.
type MockTransactionServiceServerMockRecorder struct {
	mock *MockTransactionServiceServer
}

// NewMockTransactionServiceServer creates a new mock instance.
func NewMockTransactionServiceServer(ctrl *gomock.Controller) *MockTransactionServiceServer {
	mock := &MockTransactionServiceServer{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionServiceServer) EXPECT() *MockTransactionServiceServerMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockTransactionServiceServer) CreateTransaction(arg0 context.Context, arg1 *pb.CreateTransactionRequest) (*pb.ApiResponseTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockTransactionServiceServerMockRecorder) CreateTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockTransactionServiceServer)(nil).CreateTransaction), arg0, arg1)
}

// DeleteTransactionPermanent mocks base method.
func (m *MockTransactionServiceServer) DeleteTransactionPermanent(arg0 context.Context, arg1 *pb.FindByIdTransactionRequest) (*pb.ApiResponseTransactionDelete, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransactionPermanent", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseTransactionDelete)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTransactionPermanent indicates an expected call of DeleteTransactionPermanent.
func (mr *MockTransactionServiceServerMockRecorder) DeleteTransactionPermanent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransactionPermanent", reflect.TypeOf((*MockTransactionServiceServer)(nil).DeleteTransactionPermanent), arg0, arg1)
}

// FindAllTransaction mocks base method.
func (m *MockTransactionServiceServer) FindAllTransaction(arg0 context.Context, arg1 *pb.FindAllTransactionRequest) (*pb.ApiResponsePaginationTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllTransaction", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllTransaction indicates an expected call of FindAllTransaction.
func (mr *MockTransactionServiceServerMockRecorder) FindAllTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllTransaction", reflect.TypeOf((*MockTransactionServiceServer)(nil).FindAllTransaction), arg0, arg1)
}

// FindByActiveTransaction mocks base method.
func (m *MockTransactionServiceServer) FindByActiveTransaction(arg0 context.Context, arg1 *pb.FindAllTransactionRequest) (*pb.ApiResponsePaginationTransactionDeleteAt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByActiveTransaction", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationTransactionDeleteAt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByActiveTransaction indicates an expected call of FindByActiveTransaction.
func (mr *MockTransactionServiceServerMockRecorder) FindByActiveTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByActiveTransaction", reflect.TypeOf((*MockTransactionServiceServer)(nil).FindByActiveTransaction), arg0, arg1)
}

// FindByCardNumberTransaction mocks base method.
func (m *MockTransactionServiceServer) FindByCardNumberTransaction(arg0 context.Context, arg1 *pb.FindByCardNumberTransactionRequest) (*pb.ApiResponseTransactions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCardNumberTransaction", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseTransactions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCardNumberTransaction indicates an expected call of FindByCardNumberTransaction.
func (mr *MockTransactionServiceServerMockRecorder) FindByCardNumberTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCardNumberTransaction", reflect.TypeOf((*MockTransactionServiceServer)(nil).FindByCardNumberTransaction), arg0, arg1)
}

// FindByIdTransaction mocks base method.
func (m *MockTransactionServiceServer) FindByIdTransaction(arg0 context.Context, arg1 *pb.FindByIdTransactionRequest) (*pb.ApiResponseTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdTransaction", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdTransaction indicates an expected call of FindByIdTransaction.
func (mr *MockTransactionServiceServerMockRecorder) FindByIdTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdTransaction", reflect.TypeOf((*MockTransactionServiceServer)(nil).FindByIdTransaction), arg0, arg1)
}

// FindByTrashedTransaction mocks base method.
func (m *MockTransactionServiceServer) FindByTrashedTransaction(arg0 context.Context, arg1 *pb.FindAllTransactionRequest) (*pb.ApiResponsePaginationTransactionDeleteAt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTrashedTransaction", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationTransactionDeleteAt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTrashedTransaction indicates an expected call of FindByTrashedTransaction.
func (mr *MockTransactionServiceServerMockRecorder) FindByTrashedTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTrashedTransaction", reflect.TypeOf((*MockTransactionServiceServer)(nil).FindByTrashedTransaction), arg0, arg1)
}

// FindTransactionByMerchantId mocks base method.
func (m *MockTransactionServiceServer) FindTransactionByMerchantId(arg0 context.Context, arg1 *pb.FindTransactionByMerchantIdRequest) (*pb.ApiResponseTransactions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTransactionByMerchantId", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseTransactions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTransactionByMerchantId indicates an expected call of FindTransactionByMerchantId.
func (mr *MockTransactionServiceServerMockRecorder) FindTransactionByMerchantId(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTransactionByMerchantId", reflect.TypeOf((*MockTransactionServiceServer)(nil).FindTransactionByMerchantId), arg0, arg1)
}

// RestoreTransaction mocks base method.
func (m *MockTransactionServiceServer) RestoreTransaction(arg0 context.Context, arg1 *pb.FindByIdTransactionRequest) (*pb.ApiResponseTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreTransaction", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreTransaction indicates an expected call of RestoreTransaction.
func (mr *MockTransactionServiceServerMockRecorder) RestoreTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreTransaction", reflect.TypeOf((*MockTransactionServiceServer)(nil).RestoreTransaction), arg0, arg1)
}

// TrashedTransaction mocks base method.
func (m *MockTransactionServiceServer) TrashedTransaction(arg0 context.Context, arg1 *pb.FindByIdTransactionRequest) (*pb.ApiResponseTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrashedTransaction", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrashedTransaction indicates an expected call of TrashedTransaction.
func (mr *MockTransactionServiceServerMockRecorder) TrashedTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrashedTransaction", reflect.TypeOf((*MockTransactionServiceServer)(nil).TrashedTransaction), arg0, arg1)
}

// UpdateTransaction mocks base method.
func (m *MockTransactionServiceServer) UpdateTransaction(arg0 context.Context, arg1 *pb.UpdateTransactionRequest) (*pb.ApiResponseTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransaction", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTransaction indicates an expected call of UpdateTransaction.
func (mr *MockTransactionServiceServerMockRecorder) UpdateTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransaction", reflect.TypeOf((*MockTransactionServiceServer)(nil).UpdateTransaction), arg0, arg1)
}

// mustEmbedUnimplementedTransactionServiceServer mocks base method.
func (m *MockTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedTransactionServiceServer")
}

// mustEmbedUnimplementedTransactionServiceServer indicates an expected call of mustEmbedUnimplementedTransactionServiceServer.
func (mr *MockTransactionServiceServerMockRecorder) mustEmbedUnimplementedTransactionServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedTransactionServiceServer", reflect.TypeOf((*MockTransactionServiceServer)(nil).mustEmbedUnimplementedTransactionServiceServer))
}

// MockUnsafeTransactionServiceServer is a mock of UnsafeTransactionServiceServer interface.
type MockUnsafeTransactionServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeTransactionServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeTransactionServiceServerMockRecorder is the mock recorder for MockUnsafeTransactionServiceServer.
type MockUnsafeTransactionServiceServerMockRecorder struct {
	mock *MockUnsafeTransactionServiceServer
}

// NewMockUnsafeTransactionServiceServer creates a new mock instance.
func NewMockUnsafeTransactionServiceServer(ctrl *gomock.Controller) *MockUnsafeTransactionServiceServer {
	mock := &MockUnsafeTransactionServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeTransactionServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeTransactionServiceServer) EXPECT() *MockUnsafeTransactionServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedTransactionServiceServer mocks base method.
func (m *MockUnsafeTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedTransactionServiceServer")
}

// mustEmbedUnimplementedTransactionServiceServer indicates an expected call of mustEmbedUnimplementedTransactionServiceServer.
func (mr *MockUnsafeTransactionServiceServerMockRecorder) mustEmbedUnimplementedTransactionServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedTransactionServiceServer", reflect.TypeOf((*MockUnsafeTransactionServiceServer)(nil).mustEmbedUnimplementedTransactionServiceServer))
}
