FROM golang:1.22-alpine AS builder

# Install protobuf compiler
RUN apk add --no-cache protobuf

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy proto files
COPY pkg/proto /app/pkg/proto

# Generate the Go code for proto
RUN protoc --proto_path=pkg/proto --go_out=internal/pb --go_opt=paths=source_relative --go-grpc_out=internal/pb --go-grpc_opt=paths=source_relative pkg/proto/*.proto

# Start a new stage from Alpine to reduce image size
FROM alpine:latest

# Copy the generated proto files from the builder image
COPY --from=builder /app/internal/pb /app/internal/pb
