name: Build and push

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        name: [ server, client, migrate ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/MamangRust/payment-gateway-grpc/${{ matrix.name }}"
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: "./docker/Dockerfile.${{ matrix.name }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}