name: Build and push

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        name: [server, client, migrate]

    steps:
     
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/MamangRust/payment-gateway-grpc/${{ matrix.name }}"
          tags: |
            type=ref,event=branch,name=main
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title=Payment Gateway gRPC
            org.opencontainers.image.description=Learning Purpose
            org.opencontainers.image.source=https://github.com/MamangRust/payment-gateway-grpc
            org.opencontainers.image.url=https://github.com/MamangRust/payment-gateway-grpc
            org.opencontainers.image.licenses=MIT

      - name: Debug Metadata Outputs
        run: |
          echo "Generated Tags: ${{ steps.meta.outputs.tags }}"
          echo "Generated Labels: ${{ steps.meta.outputs.labels }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_TOKEN }}

     
      - name: Debug Build Context
        run: |
          echo "Dockerfile Path: ./docker/Dockerfile.${{ matrix.name }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: "./docker/Dockerfile.${{ matrix.name }}"
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/MamangRust/payment-gateway-grpc/${{ matrix.name }}:latest
          labels: ${{ steps.meta.outputs.labels }}
